
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA ID INIT LABEL LBRACE LPAREN NUMBER RBRACE RPAREN SEMICOLON STATES TRANS VALUESkripke : states_decl init_decl trans_decl label_decl values_declstates_decl : STATES COLON LBRACE id_list RBRACE SEMICOLONinit_decl : INIT COLON LBRACE id_list RBRACE SEMICOLONtrans_decl : TRANS COLON LBRACE trans_list RBRACE SEMICOLONtrans_list : trans_pair\n                 | trans_pair COMMA trans_listtrans_pair : LPAREN ID COMMA ID RPARENlabel_decl : LABEL COLON LBRACE label_list RBRACE SEMICOLONlabel_list : label_assignment\n                 | label_assignment COMMA label_listlabel_assignment : ID COLON LBRACE id_list RBRACEvalues_decl : VALUES COLON LBRACE value_list RBRACE SEMICOLONvalue_list : value_assignment\n                 | value_assignment COMMA value_listvalue_assignment : ID COLON NUMBERid_list : ID\n               | ID COMMA id_list'
    
_lr_action_items = {'STATES':([0,],[3,]),'$end':([1,17,56,],[0,-1,-12,]),'INIT':([2,30,],[5,-2,]),'COLON':([3,5,8,12,18,35,42,],[6,9,13,19,24,45,51,]),'TRANS':([4,39,],[8,-3,]),'LBRACE':([6,9,13,19,24,45,],[10,14,20,25,32,54,]),'LABEL':([7,46,],[12,-4,]),'ID':([10,14,23,25,28,32,44,48,50,54,],[16,16,16,35,38,42,35,55,42,16,]),'VALUES':([11,52,],[18,-8,]),'RBRACE':([15,16,21,26,27,31,33,34,40,41,47,53,57,58,59,60,61,],[22,-16,29,36,-5,-17,43,-9,49,-13,-6,-10,-14,-15,61,-7,-11,]),'COMMA':([16,27,34,38,41,58,60,61,],[23,37,44,48,50,-15,-7,-11,]),'LPAREN':([20,37,],[28,28,]),'SEMICOLON':([22,29,36,43,49,],[30,39,46,52,56,]),'NUMBER':([51,],[58,]),'RPAREN':([55,],[60,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'kripke':([0,],[1,]),'states_decl':([0,],[2,]),'init_decl':([2,],[4,]),'trans_decl':([4,],[7,]),'label_decl':([7,],[11,]),'id_list':([10,14,23,54,],[15,21,31,59,]),'values_decl':([11,],[17,]),'trans_list':([20,37,],[26,47,]),'trans_pair':([20,37,],[27,27,]),'label_list':([25,44,],[33,53,]),'label_assignment':([25,44,],[34,34,]),'value_list':([32,50,],[40,57,]),'value_assignment':([32,50,],[41,41,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> kripke","S'",1,None,None,None),
  ('kripke -> states_decl init_decl trans_decl label_decl values_decl','kripke',5,'p_kripke','parser.py',5),
  ('states_decl -> STATES COLON LBRACE id_list RBRACE SEMICOLON','states_decl',6,'p_states_decl','parser.py',15),
  ('init_decl -> INIT COLON LBRACE id_list RBRACE SEMICOLON','init_decl',6,'p_init_decl','parser.py',19),
  ('trans_decl -> TRANS COLON LBRACE trans_list RBRACE SEMICOLON','trans_decl',6,'p_trans_decl','parser.py',23),
  ('trans_list -> trans_pair','trans_list',1,'p_trans_list','parser.py',27),
  ('trans_list -> trans_pair COMMA trans_list','trans_list',3,'p_trans_list','parser.py',28),
  ('trans_pair -> LPAREN ID COMMA ID RPAREN','trans_pair',5,'p_trans_pair','parser.py',32),
  ('label_decl -> LABEL COLON LBRACE label_list RBRACE SEMICOLON','label_decl',6,'p_label_decl','parser.py',36),
  ('label_list -> label_assignment','label_list',1,'p_label_list','parser.py',40),
  ('label_list -> label_assignment COMMA label_list','label_list',3,'p_label_list','parser.py',41),
  ('label_assignment -> ID COLON LBRACE id_list RBRACE','label_assignment',5,'p_label_assignment','parser.py',45),
  ('values_decl -> VALUES COLON LBRACE value_list RBRACE SEMICOLON','values_decl',6,'p_values_decl','parser.py',49),
  ('value_list -> value_assignment','value_list',1,'p_value_list','parser.py',53),
  ('value_list -> value_assignment COMMA value_list','value_list',3,'p_value_list','parser.py',54),
  ('value_assignment -> ID COLON NUMBER','value_assignment',3,'p_value_assignment','parser.py',58),
  ('id_list -> ID','id_list',1,'p_id_list','parser.py',62),
  ('id_list -> ID COMMA id_list','id_list',3,'p_id_list','parser.py',63),
]
