
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA EQUALS ID LBRACE LPAREN NUMBER RBRACE RPAREN\n    input : states_decl\n          | initstate_decl\n          | edges_decl\n          | logicalformulas_decl\n          | values_decl\n    states_decl : ID EQUALS LBRACE id_list RBRACEinitstate_decl : ID EQUALS IDedges_decl : ID EQUALS LBRACE edge_list RBRACE\n    edge_list : edge\n              | edge COMMA edge_list\n    edge : LPAREN ID COMMA ID RPARENlogicalformulas_decl : ID EQUALS LBRACE formula_list RBRACE\n    formula_list : formula\n                | formula COMMA formula_list\n    formula : ID COLON LBRACE id_list RBRACE\n               | ID COLON LBRACE RBRACEvalues_decl : value_list\n    value_list : value\n              | value COMMA value_list\n    value : ID EQUALS NUMBERid_list : ID\n               | ID COMMA id_list\n               | '
    
_lr_action_items = {'ID':([0,10,11,13,23,25,31,35,39,],[7,12,16,17,32,33,38,33,42,]),'$end':([1,2,3,4,5,6,8,9,12,14,15,27,28,29,],[0,-1,-2,-3,-4,-5,-17,-18,-7,-20,-19,-6,-8,-12,]),'EQUALS':([7,16,],[10,24,]),'COMMA':([9,14,17,21,22,32,33,41,43,44,],[11,-20,25,30,31,39,25,-16,-15,-11,]),'LBRACE':([10,26,],[13,35,]),'NUMBER':([10,24,],[14,14,]),'RBRACE':([13,17,18,19,20,21,22,25,33,34,35,36,37,40,41,43,44,],[-23,-21,27,28,29,-9,-13,-23,-21,-22,41,-10,-14,43,-16,-15,-11,]),'LPAREN':([13,30,],[23,23,]),'COLON':([17,38,],[26,26,]),'RPAREN':([42,],[44,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'states_decl':([0,],[2,]),'initstate_decl':([0,],[3,]),'edges_decl':([0,],[4,]),'logicalformulas_decl':([0,],[5,]),'values_decl':([0,],[6,]),'value_list':([0,11,],[8,15,]),'value':([0,11,],[9,9,]),'id_list':([13,25,35,],[18,34,40,]),'edge_list':([13,30,],[19,36,]),'formula_list':([13,31,],[20,37,]),'edge':([13,30,],[21,21,]),'formula':([13,31,],[22,22,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> states_decl','input',1,'p_input','parser.py',6),
  ('input -> initstate_decl','input',1,'p_input','parser.py',7),
  ('input -> edges_decl','input',1,'p_input','parser.py',8),
  ('input -> logicalformulas_decl','input',1,'p_input','parser.py',9),
  ('input -> values_decl','input',1,'p_input','parser.py',10),
  ('states_decl -> ID EQUALS LBRACE id_list RBRACE','states_decl',5,'p_states_decl','parser.py',15),
  ('initstate_decl -> ID EQUALS ID','initstate_decl',3,'p_initstate_decl','parser.py',19),
  ('edges_decl -> ID EQUALS LBRACE edge_list RBRACE','edges_decl',5,'p_edges_decl','parser.py',23),
  ('edge_list -> edge','edge_list',1,'p_edge_list','parser.py',28),
  ('edge_list -> edge COMMA edge_list','edge_list',3,'p_edge_list','parser.py',29),
  ('edge -> LPAREN ID COMMA ID RPAREN','edge',5,'p_edge','parser.py',34),
  ('logicalformulas_decl -> ID EQUALS LBRACE formula_list RBRACE','logicalformulas_decl',5,'p_logicalformulas_decl','parser.py',38),
  ('formula_list -> formula','formula_list',1,'p_formula_list','parser.py',43),
  ('formula_list -> formula COMMA formula_list','formula_list',3,'p_formula_list','parser.py',44),
  ('formula -> ID COLON LBRACE id_list RBRACE','formula',5,'p_formula','parser.py',49),
  ('formula -> ID COLON LBRACE RBRACE','formula',4,'p_formula','parser.py',50),
  ('values_decl -> value_list','values_decl',1,'p_values_decl','parser.py',57),
  ('value_list -> value','value_list',1,'p_value_list','parser.py',62),
  ('value_list -> value COMMA value_list','value_list',3,'p_value_list','parser.py',63),
  ('value -> ID EQUALS NUMBER','value',3,'p_value','parser.py',68),
  ('id_list -> ID','id_list',1,'p_id_list','parser.py',72),
  ('id_list -> ID COMMA id_list','id_list',3,'p_id_list','parser.py',73),
  ('id_list -> <empty>','id_list',0,'p_id_list','parser.py',74),
]
